POST http://localhost:3000/goods HTTP/1.1
content-type: application/json

{
    "id":"3",
    "user_id":"myantyu",
    "category_id":"0",
    "memo":"tesaaaaat"
}

# GET http://localhost:3000/comments HTTP/1.1

# GET http://localhost:3000/api/user HTTP/1.1
# # GET http://localhost:3000/user HTTP/1.1

GET http://localhost:3000/api/goods HTTP/1.1
# GET http://localhost:3000/api/goods?uesr_id=demo HTTP/1.1
# GET http://localhost:3000/goods?uesr_id=demo HTTP/1.1

# docker run --name json-server -p 3000:3000 -v `pwd`/db:/data json-server